# This file contains configuration information for the provisioning scripts.
fpga:
    nexys4:
        # Nexys 4 serial can easily be acquired though execution of:
        # $ lsusb -d 0403:6010 -v | grep iSerial
        usb_serial_number: 123456789012


files:
    # Vivado installers archives. Better to change these to absolute paths.
    # Download url:
    #  - https://www.xilinx.com/support/download.html
    # More specifically:
    #  - https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2016-4.html
    #  - https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2016-3.html
    #  - https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2016-2.html
    #  - https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vivado-design-tools/2016-1.html

    # Vivado lab edition Linux:
    xilinx_vivado_lab_lin_2016_04: ~/Downloads/Xilinx_Vivado_Lab_Lin_2016.4_0124_1.tar.gz
    xilinx_vivado_lab_lin_2016_03: ~/Downloads/Xilinx_Vivado_Lab_Lin_2016.3_1011_1.tar.gz
    xilinx_vivado_lab_lin_2016_02: ~/Downloads/Xilinx_Vivado_Lab_Lin_2016.2_0605_1.tar.gz
    xilinx_vivado_lab_lin_2016_01: ~/Downloads/Xilinx_Vivado_Lab_Lin_2016.1_0409_1.tar.gz

    # Vivado lab edition Windows:
    xilinx_vivado_lab_win_2016_04: ~/Downloads/Xilinx_Vivado_Lab_Win_2016.4_0124_1.tar.gz
    xilinx_vivado_lab_win_2016_03: ~/Downloads/Xilinx_Vivado_Lab_Win_2016.3_1011_1.tar.gz
    xilinx_vivado_lab_win_2016_02: ~/Downloads/Xilinx_Vivado_Lab_Win_2016.2_0605_1.tar.gz
    xilinx_vivado_lab_win_2016_01: ~/Downloads/Xilinx_Vivado_Lab_Win_2016.1_0409_1.tar.gz

    # Vivado HLx All OS installer Single-File Download
    xilinx_vivado_editions_2016_04: ~/Downloads/Xilinx_Vivado_SDK_2016.4_0124_1.tar.gz
    xilinx_vivado_editions_2016_03: ~/Downloads/Xilinx_Vivado_SDK_2016.3_1011_1.tar.gz
    xilinx_vivado_editions_2016_02: ~/Downloads/Xilinx_Vivado_SDK_2016.2_0605_1.tar.gz
    xilinx_vivado_editions_2016_01: ~/Downloads/Xilinx_Vivado_SDK_2016.1_0409_1.tar.gz



