# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

require 'yaml'

config = YAML.load_file(File.join('..', 'config.yaml'))
nexus4_usb_serial_number = config['fpga']['nexys4']['usb_serial_number']
vivado_lab_installer_path = config['files']['xilinx_vivado_lab_lin_2016_04']
vivado_lab_installer_dir = File.dirname(vivado_lab_installer_path)
vivado_lab_installer_filename = File.basename(vivado_lab_installer_path)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder vivado_lab_installer_dir, "/vivado_lab_installer"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    # Pass through nexys4 usb to vm
    vb.customize ['modifyvm', :id, '--usb', 'on']
    vb.customize ['modifyvm', :id, '--usbehci', 'on']
    vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'nexys4', '--serialnumber', nexus4_usb_serial_number]
  end


#  config.vm.provision "file" do |f|
#    f.source = vivado_lab_installer_path
#    f.destination = '/home/ubuntu/vivado_lab_installer.tar.gz'
#  end
  
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.path = "install_vivado.sh"
    s.env = {VIVADO_INSTALLER: '/vivado_lab_installer/' + vivado_lab_installer_filename}
  end
  
  config.vm.provision "shell" do |s|
    s.privileged = true
    s.path = "install_cable_drivers.sh"
  end
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
